baseURL = "http://pedromadureira.xyz/"
languageCode = "en-us"
title = "Pedro Madureira"
theme = "dark_lekh"
paginate = 10

[params]
  Name = "Pedro Madureira"
  About = "This is my personal website. I may post something here later."
  Email = "contact@pedromadureira.xyz"
  Resume = "" # Add the filename with file extension.
  PostLimit = 4 # Sets the number of posts to display on the front page
  GoatCounterCode = ""

[[params.profiles]]
  name = "GitHub"
  url = "https://github.com/pedromadureira000"

[[params.profiles]]
  name = "Youtube"
  url = "https://www.youtube.com/@DiverseStudiesWithPeter"


[[params.profiles]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/ph-web-solutions/"
